export const events = [
  {
    slug: 'google-io-2025',
    title: 'Google I/O 2025',
    image: '/images/event1.png',
    date: 'May 20–21, 2025',
    time: '10:00 AM PDT',
    location: 'Shoreline Amphitheatre, Mountain View, CA',
  },
  {
    slug: 'aws-re-invent-2025',
    title: 'AWS re:Invent 2025',
    image: '/images/event2.png',
    date: 'December 1–5, 2025',
    time: '9:00 AM PST',
    location: 'The Venetian, Las Vegas, NV',
  },
  {
    slug: 'vercel-ship-2025',
    title: 'Vercel Ship 2025',
    image: '/images/event3.png',
    date: 'June 3, 2025',
    time: '11:00 AM EDT',
    location: 'Online & San Francisco, CA',
  },
  {
    slug: 'github-universe-2025',
    title: 'GitHub Universe 2025',
    image: '/images/event4.png',
    date: 'October 28–29, 2025',
    time: '9:00 AM PDT',
    location: 'Fort Mason Center, San Francisco, CA',
  },
  {
    slug: 'mlh-hackathon-nyc',
    title: 'MLH Hackathon NYC 2025',
    image: '/images/event5.png',
    date: 'August 8–10, 2025',
    time: '6:00 PM EDT',
    location: 'Columbia University, New York, NY',
  },
  {
    slug: 'next-js-conf-2025',
    title: 'Next.js Conf 2025',
    image: '/images/event6.png',
    date: 'October 23, 2025',
    time: '10:00 AM PDT',
    location: 'Online & San Francisco, CA',
  },
]
